version: '2'

services:
  global:
    image: blacktourmaline/global:1.3
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: sqldbs=1
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
      
  hostfootprint:
    image: blacktourmaline/hostfootprint:1.3
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: sqldbs=1
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8001:8000"
