# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('PAIS', models.CharField(blank=True, choices=[('ARGENTINA', 'ARGENTINA'), ('BRASIL', 'BRASIL'), ('CHILE', 'CHILE'), ('COLOMBIA', 'COLOMBIA'), ('PERU', 'PERU'), ('REGIONAL', 'REGIONAL'), ('SIN ASIGNAR', 'SIN ASIGNAR')], max_length=11)),
                ('NAGIOS', models.CharField(max_length=18, null=True)),
                ('APM', models.CharField(max_length=6, null=True)),
                ('HOSTNAME', models.CharField(max_length=29, null=True)),
                ('IP', models.CharField(max_length=15, null=True)),
                ('MAC', models.CharField(max_length=17, null=True)),
                ('SO', models.CharField(max_length=19, null=True)),
                ('SO_VERSION', models.CharField(max_length=26, null=True)),
                ('SO_PROVEEDOR', models.CharField(max_length=22, null=True)),
                ('UUNN', models.CharField(choices=[('AVENTURA', 'AVENTURA'), ('BI', 'BI'), ('CENTRAL', 'CENTRAL'), ('FIDELIDAD', 'FIDELIDAD'), ('MEJORAMIENTO DEL HOGAR', 'MEJORAMIENTO DEL HOGAR'), ('N/D', 'N/D'), ('OPERACIONES', 'OPERACIONES'), ('PORTAL', 'PORTAL'), ('RETAIL FINANCIERO', 'RETAIL FINANCIERO'), ('RRHH', 'RRHH'), ('SHOPPING', 'SHOPPING'), ('SIN ASIGNAR', 'SIN ASIGNAR'), ('SUPERMERCADO', 'SUPERMERCADO'), ('TELETICKET', 'TELETICKET'), ('TIENDAS POR DEPARTAMENTO', 'TIENDAS POR DEPARTAMENTO')], max_length=24, null=True)),
                ('Es_Virtual', models.CharField(max_length=7, null=True)),
                ('En_Ope', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=2, null=True)),
                ('AMBIENTE', models.CharField(blank=True, choices=[('#N/A', '#N/A'), ('CAPACITACION', 'CAPACITACION'), ('CERTIFICACION', 'CERTIFICACION'), ('CONTINGENCIA', 'CONTINGENCIA'), ('DESARROLLO', 'DESARROLLO'), ('HISTORICO', 'HISTORICO'), ('HOMOLOGACION', 'HOMOLOGACION'), ('INTEGRACION', 'INTEGRACION'), ('LABORATORIO', 'LABORATORIO'), ('PIVOTE', 'PIVOTE'), ('PRE PRODUCCION', 'PRE PRODUCCION'), ('PRODUCCION', 'PRODUCCION'), ('PROYECTO', 'PROYECTO'), ('QA', 'QA'), ('SIN ASIGNAR', 'SIN ASIGNAR'), ('STAGE', 'STAGE'), ('STAND BY', 'STAND BY'), ('TEST', 'TEST'), ('TRAINING', 'TRAINING')], max_length=14)),
                ('ROL', models.CharField(max_length=25, null=True)),
                ('SERVICIO', models.CharField(max_length=17, null=True)),
                ('APLICACION', models.CharField(max_length=45, null=True)),
                ('KPI', models.CharField(max_length=7, null=True)),
                ('FUNCIONAL', models.CharField(max_length=44, null=True)),
                ('ROS', models.CharField(max_length=97, null=True)),
                ('LIDER_DATACENTER', models.CharField(max_length=23, null=True)),
                ('OIT', models.CharField(max_length=7, null=True)),
                ('DOC', models.CharField(max_length=189, null=True)),
                ('OBS', models.CharField(max_length=10, null=True)),
                ('IMAGEN', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
