# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessunit', models.CharField(max_length=100, unique=True, verbose_name='Business Unit')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=40, unique=True, verbose_name='City')),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(max_length=100, unique=True, verbose_name='Flag')),
                ('businessunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.BusinessUnit')),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.CharField(default='BB200', max_length=200, unique=True, verbose_name='Local ID')),
                ('local_address', models.CharField(default='Street xxx, 2020', max_length=200)),
                ('local_desc', models.CharField(blank=True, max_length=100, verbose_name='Description')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Latitud')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Longitud')),
                ('activo', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.City')),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Flag')),
            ],
        ),
    ]
