# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(default='172.18.148.0/24', max_length=26, unique=True)),
                ('description', models.CharField(blank=True, default='VLAN VoIP', max_length=150, null=True, verbose_name='vlan description')),
                ('total_subnetworks', models.IntegerField(default=0)),
                ('good_networks', models.BooleanField(default=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Local')),
            ],
        ),
    ]
